[k8s_control]
192.168.1.101

[k8s_workers]
192.168.1.102
192.168.1.103

[k8s_cluster:children]
k8s_control
k8s_workers

[k8s_cluster:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/proxmox
ansible_python_interpreter=/usr/bin/python3

